### ISSUE TITLE
Maphack function not working

### ISSUE THREAD

**Issue by newwide** [darksoul577/ReShade#1]
Enemy particles not rendered in fog.

**Comment by snajdovski** [comment]
False, it does work

**Comment by darksoul577** [comment]
> False, it does work

Thanks for checking it- sometimes the vtable offsets get updated in the patches and so our code offfsets need to be changed to match.  Newwide the fastest way to confirm its working is to demo a hero and spawn a bot. Have the bot tp into the fog and see if their tp in the fog is visible.

**Comment by snajdovski** [comment]
> > False, it does work
> 
> Thanks for checking it- sometimes the vtable offsets get updated in the patches and so our code offfsets need to be changed to match. Newwide the fastest way to confirm its working is to demo a hero and spawn a bot. Have the bot tp into the fog and see if their tp in the fog is visible.

Just did that 10 min ago :) on alt acc, everything seems to be good. Do you have Discord/email/telegram I want to ask you for help I have found some intresting stuff in source 2.

**Comment by darksoul577** [comment]
I posted this code on the guidedhacking.com site as well.  You can pm me there if you'd like. https://guidedhacking.com/threads/dota-2-cheats-maphack-illusion-detector-vision-detector.15840/

Also check out the github site for LWSS, he's very responsive to dota questions and keeps his cheats up to date. I don't play dota any more so it's unlikely ill do further development for that game. https://github.com/LWSS/McDota

**Comment by newwide** [comment]
> I posted this code on the guidedhacking.com site as well. You can pm me there if you'd like. https://guidedhacking.com/threads/dota-2-cheats-maphack-illusion-detector-vision-detector.15840/
> 
> Also check out the github site for LWSS, he's very responsive to dota questions and keeps his cheats up to date. I don't play dota any more so it's unlikely ill do further development for that game. https://github.com/LWSS/McDota

Thanks, tp detection seems fine. https://ibb.co/Wfnz70W . But is it normal if no particle is shown in the fog? Like I can't see anything in the fog except TP.

**Comment by newwide** [comment]
> > False, it does work
> 
> Thanks for checking it- sometimes the vtable offsets get updated in the patches and so our code offfsets need to be changed to match. Newwide the fastest way to confirm its working is to demo a hero and spawn a bot. Have the bot tp into the fog and see if their tp in the fog is visible.

Thanks, tp detection seems fine. https://ibb.co/Wfnz70W . But is it normal if no particle is shown in the fog? Like I can't see anything in the fog except TP.

> I posted this code on the guidedhacking.com site as well. You can pm me there if you'd like. https://guidedhacking.com/threads/dota-2-cheats-maphack-illusion-detector-vision-detector.15840/
> 
> Also check out the github site for LWSS, he's very responsive to dota questions and keeps his cheats up to date. I don't play dota any more so it's unlikely ill do further development for that game. https://github.com/LWSS/McDota

I saw your guidedhacking thread there, but I am a free user, so no PM or reply for me haha

**Comment by darksoul577** [comment]
You won't see the bounding boxes in the fog since the server is not sending the hero location to all of the clients. You will see smoke usage, spells,  and the blood spray from Roshan and neutral farming though. There's a pay hack called ensage that draws icons for these particle effects on the minimap. So that is possible to code, but you would need to add-in that functionality yourself

**Comment by snajdovski** [comment]
@darksoul577, how hard would it be to draw simple shapes over these particles?

**Comment by darksoul577** [comment]
The vtable for each larticle has a function that you can call to get the world location for the particle. You would have to convert that to a screen x y coordinate using a view matrix. LWSS gets the view matrix in his dota hack, so his code may be helpful for you. Of course, his code is for Linux so you'd have to update it for windows
