### ISSUE TITLE
Trying to find the offset

### ISSUE THREAD

**Issue by newwide** [darksoul577/ReShade#5]
The offset has changed since the halloween update.

I could not find the function graph that is identical to previous version. The most similar I can find is this.
![image](https://user-images.githubusercontent.com/69209831/97712633-aad1ff00-1af9-11eb-8b96-75fe7c25284b.png)
![image](https://user-images.githubusercontent.com/69209831/97712733-ce954500-1af9-11eb-8778-67bc8b1f34dc.png)
Which is the 203rd offset of C_BaseModelEntity vftable.(18215E0F0 - 18215DA98)

**Comment by darksoul577** [comment]
Nice job- that is the right offset :)

**Comment by darksoul577** [comment]
Updated the entity vfunc file just now. Havent  tested the change but am confident it should work.

**Comment by newwide** [comment]
Glad i found the correct offset :). About the code  changed, can we just remove any virtual void function to move forward the visible function?

**Comment by darksoul577** [comment]
Yes. The only other entity vfuncs  we use are at offsets 0 and 13. Every vfunc between offset 13 and 203 is just a placeholder.

**Comment by newwide** [comment]
Really much appreciated. Glad to have you 💯

**Comment by zorelix** [comment]
im having trouble finding the new offset of the new update :( ive spend 6hrs working on the reshade so i can use it again but no luck

**Comment by ravejuegos** [comment]
any help with this :(

**Comment by darksoul577** [comment]
> any help with this :(

Sorry man, I've moved on to other games. Dead project
